import 'dart:async';
import 'dart:io';
import 'package:flutter/foundation.dart';

// ─────────────────────────────────────────────────────────────────────────────
// خدمة aetheridle — تدير مؤقتات خمول الشاشة عبر aetheridle CLI
//
// aetheridle هو daemon خفيف يستخدم بروتوكول ext-idle-notify-v1 الرسمي
// لـ Wayland، ويعمل مع كل من Sway وHyprland.
//
// الملف المستخدم: ~/.config/aetheridle/config
// صيغة الأوامر:
//   timeout <seconds> <idle_cmd>
//   timeout <seconds> <idle_cmd> resume <resume_cmd>
//
// مثال:
//   timeout 300 "systemctl suspend"
// ─────────────────────────────────────────────────────────────────────────────

/// أوامر الخمول المدعومة
class AetheridleTimeout {
  final int seconds;
  final String idleCmd;
  final String? resumeCmd;

  const AetheridleTimeout({
    required this.seconds,
    required this.idleCmd,
    this.resumeCmd,
  });

  /// يحول إلى سطر في ملف config
  String toConfigLine() {
    final buf = StringBuffer('timeout $seconds "$idleCmd"');
    if (resumeCmd != null && resumeCmd!.isNotEmpty) {
      buf.write(' resume "$resumeCmd"');
    }
    return buf.toString();
  }

  @override
  String toString() => toConfigLine();
}

// ═══════════════════════════════════════════════════════════════════════════════

class AetheridleService {
  Process? _process;
  static const _configSubpath = '.config/aetheridle/config';

  /// مسار ملف config
  String get _configPath {
    final home = Platform.environment['HOME'] ?? '/root';
    return '$home/$_configSubpath';
  }

  // ─────────────────────────────────────────────────────────────────────────
  // قراءة الـ config
  // ─────────────────────────────────────────────────────────────────────────

  /// يقرأ ملف config ويُعيد قائمة المهلات المضبوطة.
  /// يُعيد قائمة فارغة إذا لم يكن الملف موجوداً أو فارغاً.
  Future<List<AetheridleTimeout>> readTimeouts() async {
    final file = File(_configPath);
    if (!await file.exists()) return [];

    final timeouts = <AetheridleTimeout>[];
    final lines = await file.readAsLines();

    for (final raw in lines) {
      final line = raw.trim();
      if (line.isEmpty || line.startsWith('#')) continue;

      final parsed = _parseTimeoutLine(line);
      if (parsed != null) timeouts.add(parsed);
    }

    return timeouts;
  }

  /// يُحلل سطراً مثل: `timeout 300 "systemctl suspend" resume "notify-send resumed"`
  AetheridleTimeout? _parseTimeoutLine(String line) {
    if (!line.startsWith('timeout ')) return null;

    // استخدام RegExp لاستخراج الأجزاء
    final re = RegExp(
      r'^timeout\s+(\d+)\s+"([^"]+)"(?:\s+resume\s+"([^"]+)")?$',
    );
    final m = re.firstMatch(line);
    if (m == null) {
      // محاولة بدون علامات اقتباس
      final reSimple = RegExp(
        r'^timeout\s+(\d+)\s+(\S+)(?:\s+resume\s+(\S+))?$',
      );
      final ms = reSimple.firstMatch(line);
      if (ms == null) return null;
      return AetheridleTimeout(
        seconds: int.tryParse(ms.group(1)!) ?? 0,
        idleCmd: ms.group(2)!,
        resumeCmd: ms.group(3),
      );
    }

    return AetheridleTimeout(
      seconds: int.tryParse(m.group(1)!) ?? 0,
      idleCmd: m.group(2)!,
      resumeCmd: m.group(3),
    );
  }

  // ─────────────────────────────────────────────────────────────────────────
  // كتابة الـ config
  // ─────────────────────────────────────────────────────────────────────────

  /// يكتب قائمة المهلات إلى ملف config ثم يعيد تشغيل aetheridle.
  Future<void> writeTimeouts(List<AetheridleTimeout> timeouts) async {
    final file = File(_configPath);
    await file.parent.create(recursive: true);

    final buffer = StringBuffer();
    buffer.writeln('# aetheridle config — generated by Settings');
    buffer.writeln('# تحرير تلقائي — يُعاد كتابته عند تغيير الإعدادات');
    buffer.writeln();
    for (final t in timeouts) {
      if (t.seconds > 0) {
        buffer.writeln(t.toConfigLine());
      }
    }

    await file.writeAsString(buffer.toString());
    debugPrint('[AetheridleService] كُتب config: $_configPath');

    await _restartAetheridle(timeouts);
  }

  /// اختصار: يضبط مهلة "قبل النوم" فقط (System Sleep).
  Future<void> setSuspendTimeout(int seconds) async {
    final current = await readTimeouts();
    // احتفظ بأي أوامر لا تتعلق بـ systemctl suspend
    final others = current
        .where((t) => !t.idleCmd.contains('suspend'))
        .toList();

    final updated = [...others];
    if (seconds > 0) {
      updated.add(AetheridleTimeout(
        seconds: seconds,
        idleCmd: 'systemctl suspend',
      ));
    }

    await writeTimeouts(updated);
  }

  /// يضبط 3 مهلات: خفوت الشاشة، إطفاء الشاشة، النوم
  Future<void> setAllTimeouts({
    required int dimSeconds,
    required int blankSeconds,
    required int suspendSeconds,
  }) async {
    final timeouts = <AetheridleTimeout>[];

    if (dimSeconds > 0) {
      timeouts.add(AetheridleTimeout(
        seconds: dimSeconds,
        idleCmd: _buildDimCmd(),
        resumeCmd: _buildUndimCmd(),
      ));
    }

    if (blankSeconds > 0) {
      timeouts.add(AetheridleTimeout(
        seconds: blankSeconds,
        idleCmd: _buildBlankCmd(),
        resumeCmd: _buildUnblankCmd(),
      ));
    }

    if (suspendSeconds > 0) {
      timeouts.add(AetheridleTimeout(
        seconds: suspendSeconds,
        idleCmd: 'systemctl suspend',
      ));
    }

    await writeTimeouts(timeouts);
  }

  // ─────────────────────────────────────────────────────────────────────────
  // أوامر الشاشة
  // ─────────────────────────────────────────────────────────────────────────

  String _buildDimCmd() {
    // يعتمد على المجمّع
    if (_isHyprland()) {
      return 'brightnessctl set 30%';
    }
    if (_isSway()) {
      return 'brightnessctl set 30%';
    }
    return 'brightnessctl set 30%';
  }

  String _buildUndimCmd() {
    return 'brightnessctl set 100%';
  }

  String _buildBlankCmd() {
    if (_isHyprland()) {
      return 'hyprctl dispatch dpms off';
    }
    if (_isSway()) {
      return "swaymsg 'output * power off'";
    }
    return 'xset dpms force off';
  }

  String _buildUnblankCmd() {
    if (_isHyprland()) {
      return 'hyprctl dispatch dpms on';
    }
    if (_isSway()) {
      return "swaymsg 'output * power on'";
    }
    return 'xset dpms force on';
  }

  bool _isHyprland() {
    final sig = Platform.environment['HYPRLAND_INSTANCE_SIGNATURE'];
    return sig != null && sig.isNotEmpty;
  }

  bool _isSway() {
    final sock = Platform.environment['SWAYSOCK'];
    return sock != null && sock.isNotEmpty;
  }

  // ─────────────────────────────────────────────────────────────────────────
  // تشغيل/إيقاف aetheridle
  // ─────────────────────────────────────────────────────────────────────────

  /// يوقف أي عملية aetheridle جارية ثم يشغّل نسخة جديدة بناءً على الـ config.
  Future<void> _restartAetheridle(List<AetheridleTimeout> timeouts) async {
    await _killAetheridle();

    if (timeouts.isEmpty || timeouts.every((t) => t.seconds <= 0)) {
      debugPrint('[AetheridleService] لا توجد مهلات — aetheridle لن يُشغَّل');
      return;
    }

    // بناء قائمة وسائط CLI
    final args = <String>[];
    for (final t in timeouts) {
      if (t.seconds <= 0) continue;
      args.addAll(['timeout', '${t.seconds}', t.idleCmd]);
      if (t.resumeCmd != null && t.resumeCmd!.isNotEmpty) {
        args.addAll(['resume', t.resumeCmd!]);
      }
    }

    if (args.isEmpty) return;

    try {
      _process = await Process.start(
        'aetheridle',
        args,
        mode: ProcessStartMode.detached,
      );
      debugPrint('[AetheridleService] شُغّل aetheridle بـ PID: ${_process!.pid}');
    } catch (e) {
      debugPrint('[AetheridleService] فشل تشغيل aetheridle: $e');
      // fallback: شغّل مع ملف config
      try {
        _process = await Process.start(
          'aetheridle',
          ['-C', _configPath],
          mode: ProcessStartMode.detached,
        );
        debugPrint('[AetheridleService] شُغّل aetheridle بالـ config (fallback)');
      } catch (e2) {
        debugPrint('[AetheridleService] فشل التشغيل بالـ config أيضاً: $e2');
      }
    }
  }

  /// يوقف جميع عمليات aetheridle الجارية.
  Future<void> _killAetheridle() async {
    // أوقف العملية المُدارة داخلياً
    if (_process != null) {
      try {
        _process!.kill();
      } catch (_) {}
      _process = null;
    }

    // أوقف أي عملية خارجية
    try {
      await Process.run('pkill', ['-x', 'aetheridle']);
      // انتظر قليلاً للتأكد من الإيقاف
      await Future.delayed(const Duration(milliseconds: 200));
    } catch (_) {}
  }

  // ─────────────────────────────────────────────────────────────────────────
  // القراءة الأولية — لتحميل الإعدادات الحالية في الـ UI
  // ─────────────────────────────────────────────────────────────────────────

  /// يُعيد قيم المهلات الحالية من ملف config (بالثواني).
  /// يُعيد {dim: 0, blank: 0, suspend: 0} إذا لم يكن الملف موجوداً.
  Future<Map<String, int>> getCurrentTimeoutsSeconds() async {
    final timeouts = await readTimeouts();
    int dim = 0, blank = 0, suspend = 0;

    for (final t in timeouts) {
      if (t.idleCmd.contains('suspend')) {
        suspend = t.seconds;
      } else if (t.idleCmd.contains('dpms off') || t.idleCmd.contains('power off')) {
        blank = t.seconds;
      } else if (t.idleCmd.contains('brightnessctl') || t.idleCmd.contains('dim')) {
        dim = t.seconds;
      }
    }

    return {'dim': dim, 'blank': blank, 'suspend': suspend};
  }

  void dispose() {
    _process?.kill();
  }
}
